
export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const GET_ENTRIES_REQUEST = 'GET_ENTRIES_REQUEST'
export const GET_ENTRIES_SUCCESS = 'GET_ENTRIES_SUCCESS'
export const GET_ENTRIES_FAIL = 'GET_ENTRIES_FAIL'

export const CREATE_ENTRY_REQUEST = 'CREATE_ENTRY_REQUEST'
export const CREATE_ENTRY_SUCCESS = 'CREATE_ENTRY_SUCCESS'
export const CREATE_ENTRY_FAIL = 'CREATE_ENTRY_FAIL'

export const UPDATE_ENTRY_REQUEST = 'UPDATE_ENTRY_REQUEST'
export const UPDATE_ENTRY_SUCCESS = 'UPDATE_ENTRY_SUCCESS'
export const UPDATE_ENTRY_FAIL = 'UPDATE_ENTRY_FAIL'

export const GET_ENTRY_REQUEST = 'GET_ENTRY_REQUEST'
export const GET_ENTRY_SUCCESS = 'GET_ENTRY_SUCCESS'
export const GET_ENTRY_FAIL = 'GET_ENTRY_FAIL'

export const DELETE_ENTRY_REQUEST = 'DELETE_ENTRY_REQUEST'
export const DELETE_ENTRY_SUCCESS = 'DELETE_ENTRY_SUCCESS'
export const DELETE_ENTRY_FAIL = 'DELETE_ENTRY_FAIL'

export const HIDE_ENTRY = 'HIDE_ENTRY'
export const FILTER_ENTRIES = 'FILTER_ENTRIES'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

